experiment:
  output_dir: artifacts/run-default
  seed: 42

logging:
  level: INFO

split:
  n_splits: 5

target:
  label: winner

data:
  raw_dir: Data/raw
  archive_files:
    results: results.csv
    winners: winners.csv
    drivers: drivers_updated.csv
    constructors: constructors.csv
    races: races.csv
    pit_stops: pit_stops.csv
    lap_times: lap_times.csv
    qualifying: qualifying.csv
  parse_dates:
    - Date

features:
  use_quali: true

model:
  name: logistic_regression # alias: logreg
  type: classification
  params:
    C: 1.0
    max_iter: 1000
    solver: lbfgs
# early_stopping: (not used)

evaluation:
  top_k: [1, 3, 5, 10]
  metrics:
    - roc_auc
    - average_precision
    - name: log_loss
      greater_is_better: false
